[package]
name = "crs-geometry"
version = "0.1.0"
authors = ["caperaven <caperaven@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
euclid = "0.22.6"