[package]
name = "crs_geometry"
version = "0.1.0"
authors = ["caperaven <caperaven@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "crs_geometry"

[dependencies]
euclid = "0.22.6"